"""add test col

Revision ID: 25cc3c390f96
Revises: 23ae6815d2a2
Create Date: 2022-04-17 01:14:14.303207

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "25cc3c390f96"
down_revision = "23ae6815d2a2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("LBG_OHLC_1DAY", sa.Column("TEST_COL", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("LBG_OHLC_1DAY", "TEST_COL")
    # ### end Alembic commands ###
