"""genesis - initialise tables

Revision ID: 96229a79420d
Revises: 
Create Date: 2022-04-16 23:41:29.230593

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "96229a79420d"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "LBG_OHLC_1DAY",
        sa.Column("ID", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("DATE", sa.DateTime(), nullable=True),
        sa.Column("OPEN", sa.Float(precision=5), nullable=True),
        sa.Column("HIGH", sa.Float(precision=5), nullable=True),
        sa.Column("LOW", sa.Float(precision=5), nullable=True),
        sa.Column("CLOSE", sa.Float(precision=5), nullable=True),
        sa.Column("ADJ_CLOSE", sa.Float(precision=5), nullable=True),
        sa.Column("VOLUME", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("ID"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("LBG_OHLC_1DAY")
    # ### end Alembic commands ###
